# Generated by Django 4.1.2 on 2022-12-03 16:56

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_pic', models.ImageField(default='images/user_profile/default12998.png', upload_to='images/user_profile')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodation_name', models.CharField(max_length=200, null=True)),
                ('price_per_night', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('image_path', models.ImageField(upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=50, null=True)),
                ('related_city', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('description', models.CharField(max_length=1500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('categories', models.CharField(choices=[('Wisata Alam', 'Wisata Alam'), ('Taman Bermain', 'Taman Bermain'), ('Tempat Bersejarah', 'Tempat Bersejarah'), ('Kebun Binatang', 'Kebun Binatang'), ('Wisata Seni', 'Wisata Seni'), ('Pusat Belanja', 'Pusat Belanja'), ('Bangunan Unik', 'Bangunan Unik')], max_length=200, null=True)),
                ('image_path', models.ImageField(upload_to='images')),
                ('address', models.CharField(max_length=200)),
                ('maps', models.CharField(max_length=1500, null=True)),
                ('panorama', models.CharField(max_length=1500, null=True)),
                ('kecamatan', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=22200, null=True)),
                ('opening_hours', models.TimeField(null=True)),
                ('closing_hours', models.TimeField(null=True)),
                ('price_min', models.IntegerField()),
                ('price_max', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Album ', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('moda', models.CharField(choices=[('BUS', 'Bus'), ('TRAIN', 'Kereta Api'), ('PLANE', 'Pesawat')], max_length=200)),
                ('depart_time', models.TimeField()),
                ('arrive_time', models.TimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('price_per_person', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.city')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_to', to='tours.city')),
            ],
        ),
        migrations.CreateModel(
            name='RencanaWisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('theme', models.CharField(choices=[('Pantai', 'Pantai'), ('Gunung', 'Gunung'), ('Tempat Bersejarah', 'Tempat Bersejarah'), ('Taman Hiburan', 'Taman Hiburan'), ('Wisata Seni', 'Wisata Seni'), ('Perkotaan', 'Perkotaan'), ('Mixed', 'Mixed')], max_length=200, null=True)),
                ('budget', models.CharField(max_length=200)),
                ('cover', models.ImageField(null=True, upload_to='images')),
                ('days', models.IntegerField()),
                ('total_cost', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('akomodasi', models.ManyToManyField(to='tours.accomodation')),
                ('city_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_dest', to='tours.city')),
                ('city_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.city')),
                ('destination', models.ManyToManyField(to='tours.destination')),
                ('transportasi_pergi', models.ManyToManyField(to='tours.transportation')),
                ('transportasi_pulang', models.ManyToManyField(related_name='transport_pulang', to='tours.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Judul', max_length=200)),
                ('image_path', models.ImageField(upload_to='images/')),
                ('caption', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('default', models.BooleanField(default=False)),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.imagealbum')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='album',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='tours.imagealbum'),
        ),
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.city'),
        ),
        migrations.AddField(
            model_name='accomodation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.city'),
        ),
    ]
