# Generated by Django 4.1.2 on 2022-10-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='related_city',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
