# Generated by Django 4.1.2 on 2022-12-07 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postingan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Judul', max_length=200)),
                ('image_path', models.ImageField(upload_to='images/post')),
                ('caption', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RencanaaWisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('budget', models.FloatField()),
                ('days', models.IntegerField()),
                ('real_cost', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RencanaWisataDestinasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rencanawisata',
            name='akomodasi',
        ),
        migrations.RemoveField(
            model_name='rencanawisata',
            name='city_dest',
        ),
        migrations.RemoveField(
            model_name='rencanawisata',
            name='city_start',
        ),
        migrations.RemoveField(
            model_name='rencanawisata',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='rencanawisata',
            name='transportasi_pergi',
        ),
        migrations.RemoveField(
            model_name='rencanawisata',
            name='transportasi_pulang',
        ),
        migrations.RenameModel(
            old_name='Accomodation',
            new_name='Akomodasi',
        ),
        migrations.RenameModel(
            old_name='Destination',
            new_name='Destinasi',
        ),
        migrations.RenameModel(
            old_name='City',
            new_name='Kota',
        ),
        migrations.RenameModel(
            old_name='Transportation',
            new_name='Transportasi',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='RencanaWisata',
        ),
        migrations.AddField(
            model_name='rencanawisatadestinasi',
            name='destinasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.destinasi'),
        ),
        migrations.AddField(
            model_name='rencanawisatadestinasi',
            name='rencana_wisata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.rencanaawisata'),
        ),
        migrations.AddField(
            model_name='rencanaawisata',
            name='akomodasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.akomodasi'),
        ),
        migrations.AddField(
            model_name='rencanaawisata',
            name='city_dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_city_dest', to='tours.kota'),
        ),
        migrations.AddField(
            model_name='rencanaawisata',
            name='city_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.kota'),
        ),
        migrations.AddField(
            model_name='rencanaawisata',
            name='destination',
            field=models.ManyToManyField(related_name='user_rencana_destinasi', through='tours.RencanaWisataDestinasi', to='tours.destinasi'),
        ),
        migrations.AddField(
            model_name='rencanaawisata',
            name='transportasi_pergi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.transportasi'),
        ),
        migrations.AddField(
            model_name='rencanaawisata',
            name='transportasi_pulang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tp_pulang', to='tours.transportasi'),
        ),
        migrations.AddField(
            model_name='rencanaawisata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
