# Generated by Django 4.1.2 on 2022-12-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_postingan_rencanaawisata_rencanawisatadestinasi_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RencanaaWisata',
            new_name='RencanaWisata',
        ),
    ]
