# Generated by Django 4.1.2 on 2022-10-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_city_related_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image_path',
            field=models.ImageField(upload_to='images'),
        ),
    ]
