# Generated by Django 4.1.2 on 2022-12-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rename_rencanaawisata_rencanawisata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kota',
            name='image',
            field=models.ImageField(null=True, upload_to='images/city'),
        ),
    ]
