# Generated by Django 4.1.2 on 2022-11-02 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_destination_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moda', models.CharField(max_length=200)),
                ('depart_time', models.TimeField()),
                ('arrive_time', models.TimeField()),
                ('price_per_person', models.IntegerField()),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.city')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_to', to='tours.city')),
            ],
        ),
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_night', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('image_path', models.ImageField(upload_to='images')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.city')),
            ],
        ),
    ]
