# Generated by Django 4.1.2 on 2022-11-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_city_description_city_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='moda',
            field=models.CharField(choices=[('BUS', 'Bus'), ('TRAIN', 'Kereta Api'), ('PLANE', 'Pesawat')], max_length=200),
        ),
    ]
