# Generated by Django 4.1.2 on 2022-11-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_transportation_moda'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
