# Generated by Django 4.1.2 on 2022-12-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_remove_kota_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tanggal_lahir',
            field=models.DateField(null=True),
        ),
    ]
