# Generated by Django 4.1.2 on 2022-11-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_transportation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
