# Generated by Django 4.1.2 on 2022-12-08 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_postingan_destinasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinasi',
            name='rating',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
