# Generated by Django 4.1.2 on 2022-12-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_destinasi_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinasi',
            name='rating',
        ),
        migrations.AddField(
            model_name='destinasi',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
