# Generated by Django 4.1.2 on 2022-11-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_destination_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='categories',
            field=models.CharField(choices=[('Wisata Alam', 'Wisata Alam'), ('Taman Bermain', 'Taman Bermain'), ('Tempat Bersejarah', 'Tempat Bersejarah'), ('Kebun Binatang', 'Kebun Binatang'), ('Wisata Seni', 'Wisata Seni'), ('Pusat Belanja', 'Pusat Belanja'), ('Bangunan Unik', 'Bangunan Unik')], max_length=200, null=True),
        ),
    ]
