# Generated by Django 4.1.2 on 2022-11-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_destination_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='categories',
            field=models.CharField(choices=[('Wisata Al am', 'Wisata Alam'), ('Taman Bermain', 'Taman Bermain'), ('Tempat Bersejarah', 'Tempat Bersejarah'), ('Kebun Binatang', 'Kebun Binatang'), ('Wisata Seni', 'Wisata Seni'), ('Pusat Belanja', 'Pusat Belanja'), ('Bangunan Unik', 'Bangunan Unik')], max_length=200, null=True),
        ),
    ]
