# Generated by Django 4.1.2 on 2022-11-17 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_city_province_alter_destination_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RencanaWisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.CharField(max_length=200)),
                ('depart', models.DateField()),
                ('retur', models.DateField()),
                ('days', models.IntegerField()),
                ('akomodasi', models.ManyToManyField(to='tours.accomodation')),
                ('city_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_dest', to='tours.city')),
                ('city_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.city')),
                ('destination', models.ManyToManyField(to='tours.destination')),
                ('transportasi', models.ManyToManyField(to='tours.transportation')),
            ],
        ),
    ]
