# Generated by Django 4.1.2 on 2022-11-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_rencanawisata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomodation',
            options={'ordering': ['accomodation_name']},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city']},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transportation',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='accomodation',
            name='accomodation_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
