# Generated by Django 4.1.2 on 2022-12-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_remove_kota_related_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='kota',
            name='related_city',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
