# Generated by Django 4.1.2 on 2022-11-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_accomodation_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomodation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transportation',
            options={},
        ),
        migrations.RemoveField(
            model_name='rencanawisata',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='rencanawisata',
            name='retur',
        ),
    ]
