# Generated by Django 4.1.2 on 2022-11-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_alter_accomodation_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rencanawisata',
            old_name='transportasi',
            new_name='transportasi_pergi',
        ),
        migrations.AddField(
            model_name='rencanawisata',
            name='transportasi_pulang',
            field=models.ManyToManyField(related_name='transport_pulang', to='tours.transportation'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='categories',
            field=models.CharField(choices=[('Wisata Alam', 'Wisata Alam'), ('Taman Bermain', 'Taman Bermain'), ('Tempat Bersejarah', 'Tempat Bersejarah'), ('Kebun Binatang', 'Kebun Binatang'), ('Wisata Seni', 'Wisata Seni'), ('Pusat Belanja', 'Pusat Belanja'), ('Bangunan Unik', 'Bangunan Unik')], max_length=200, null=True),
        ),
    ]
