# Generated by Django 4.1.2 on 2022-11-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_rename_transportasi_rencanawisata_transportasi_pergi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='kecamatan',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rencanawisata',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rencanawisata',
            name='total_cost',
            field=models.IntegerField(null=True),
        ),
    ]
