# Generated by Django 4.1.2 on 2022-11-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_imagealbum_image_destination_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(),
        ),
    ]
