# Generated by Django 4.1.2 on 2022-11-18 04:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_alter_destination_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
