# Generated by Django 4.1.2 on 2022-11-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_alter_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='maps',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='panorama',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
