# Generated by Django 4.1.2 on 2022-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_destination_maps_destination_panorama'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencanawisata',
            name='theme',
            field=models.CharField(choices=[('Pantai', 'Pantai'), ('Gunung', 'Gunung'), ('Tempat Bersejarah', 'Tempat Bersejarah'), ('Taman Hiburan', 'Taman Hiburan'), ('Wisata Seni', 'Wisata Seni'), ('Perkotaan', 'Perkotaan'), ('Mixed', 'Mixed')], max_length=200, null=True),
        ),
    ]
