# Generated by Django 4.1.2 on 2022-11-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_rencanawisata_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencanawisata',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
