# Generated by Django 4.1.2 on 2022-12-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0022_accomodation_created_at_accomodation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagealbum',
            name='name',
            field=models.CharField(default='Album ', max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.CharField(max_length=22200, null=True),
        ),
        migrations.AlterField(
            model_name='rencanawisata',
            name='cover',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
