from .UserProfile import *
from .RencanaWisata import *
from .Login import *
from .PostsController import *
from .CreatePost import *
from .RegisterController import *
from .IndexPost import *
from .IndexController import *
from .IndexDestinasi import *
from .IndexRencanaWisata import *
from .DetailDestinasi import *
from .PostDelete import *
from .UpdatePost import *
from .CreatePost import *
